export const ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_DATE: 'SET_DATE',
  SET_VALUE: 'SET_VALUE',
  SET_ARRTODO: 'SET_ARRTODO',
  SET_MONTH: 'SET_MONTH',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_EMAIL: 'SET_EMAIL'
};
